#cloud-config
users:
  - name: appuser
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDqZt4YB9y66fWf956T2+7g7ZuzVf/nSxa7pieoTMDOPt+MraABHNQwPPPqPGI+8uX6p0tLIEB+2Rq4vQNkpJx4m2gl/F+EfF+lM5rgCrQjFT9RsxhZqY7Jx5ECqHn356ASc19sdy0mNODaOcpefavB+JtynQQORZPTSEYCi97VgX2kBjVQZ6XrUc4jXwKJzWrcD2HJpygRiYzApWrsRCzoiBVbcNWGfbUZ8nEyQEvO45GaP71jqBmTfbGnoomsaJ8vqOJDgaTojDA/Z4GEJvNRp3CaldyVRPlMNUQSEI+BZAu5uxr0ZJFRpIVWFQqIe7MjXZPHz3wDYJJ8YcYrxtl9 appuser

runcmd:
 - wget -q https://github.com/Otus-DevOps-2022-02/Yerlan-ops_infra/blob/cloud-testapp/install_mongodb.sh
 - wget -q https://github.com/Otus-DevOps-2022-02/Yerlan-ops_infra/blob/cloud-testapp/install_ruby.sh
 - wget -q https://github.com/Otus-DevOps-2022-02/Yerlan-ops_infra/blob/cloud-testapp/deploy.sh
 - bash chmod 770 install_ruby
 - bash chmod 770 install_mongodb
 - bash chmod 770 deploy.sh
 - bash install_ruby.sh
 - bash install_mongodb.sh
 - bash deploy.sh
